services:
  backend:
    image: zachshr/codebuddy-backend:latest
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
  

  frontend:
    image: zachshr/codebuddy-frontend:latest
    build: ./frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://172.31.44.235:8000
    depends_on:
      - backend
    
